### ISSUE TITLE
"Recursively allocating memory" / "Grabbing blocks of memory"

### ISSUE THREAD

**Issue by mundya** [project-rig/rig#68] opened 2015-03-16 16:51 UTC
The `MachineController` provides `sdram_alloc_as_io` as a way of allocating a block of memory and then getting a file-like view of that block of memory.  Sadly, because the tag ~~table~~ range is quite small we're generally going to be limited to performing 1 alloc per core and then laying out that larger block of memory much as we currently do (with something like a pointer table at the start).  I've been trying to think of ways of making this nicer to work with from the host and one thing I was considering was extending `MemoryIO` so that it has a method which means something like "give me the next _n_ bytes of memory as a new `MemoryIO` and move the current pointer to the end of that block".

E.g.:
```python
>>> mem = cn.sdram_alloc_as_io(1024, tag=1)  # I now have 1kB of SDRAM as a file-like
>>> mem1 = mem.alloc_next(400)  # `mem1` is a 400 byte block = mem[0:400]
>>> mem.tell()
400
```

The result is that building an application pointer table can occur alongside getting a different file-like view for each region in the allocated region of SDRAM.

```python
region_lengths = [100, 300, 400, 500]
mem_overall = cn.sdram_alloc_as_io(sum(region_lengths) + len(region_lengths)*4 + APP_PTR_HEADER_LENGTH)
mem_app_ptr = mem_overall.alloc_next(APP_PTR_HEADER_LENGTH + 4*len(region_lengths))
mem_app_ptr.seek(APP_PTR_HEADER_LENGTH)

regions = []
for length in region_lengths:
    mem_app_ptr.write(mem_overall.tell())
    regions.append(mem_overall.alloc_next(length))
```

Some questions:
 - Does this seem like a good idea?
 - Can we think of a better name than `alloc_next` or `alloc_next_as_io`?

**Comment by mossblaser** [comment] 2015-03-16 19:13
I like the idea, however this seems like a perfect opportunity to use the (rig) Region abstraction. Make a region which accepts a set of regions and it generates the lookup table at the start and can be dumped into a single malloc'd block. `ContainerRegion` perhaps?

**Comment by mundya** [comment] 2015-03-16 19:53
True, I'm definitely more trying to think of a nice way of getting a smaller block of memory out of a `MemoryIO`. How does this seem for that?

**Comment by mossblaser** [comment] 2015-03-17 10:04
I'm not sure I understand the specific motivation? Since the application need only grab a pointer to the pointer table (requring one tag per core), couldn't further allocations can be made by native sdram_alloc_as_io calls (without tags)?

**Comment by mundya** [comment] 2015-03-17 10:09
I was motivated by something like "I have a huge block of memory but I'd like to be able to pass a chunk of that off to something else that shouldn't have access to this entire block".  Using it to build up the app_ptr table was just a (poorly chosen) example.

**Comment by mossblaser** [comment] 2015-03-17 10:24
Could you give an alternative example? /me is struggling to see an application.

One thing which many libraries/languages have is the ability to produce "slices" of existing arrays, perhaps doing mem_overall[0:350] should return a new MemoryIO with access just to that subset?

**Comment by mundya** [comment] 2015-03-17 10:38
This basically is `mem_overall[0:350]` and I'd be happy providing that as an alternative interface.

One example would be in Nengo/SpiNNaker where you need to read back data from SDRAM after simulation but shouldn't care about the implementation of app_ptr tables, so you just store a `MemoryIO` object which describes the region of memory you need to read back from.  This is possible using the current API (you create new `MemoryIO` and instantiate it with the correct start and end addresses) but this just wraps that up into something a little nicer.  Slicing would do a similar thing.

**Comment by mossblaser** [comment] 2015-03-17 10:48
Are you reading back only subsets of regions in nengo? If not, using sdram_alloc for each region and just keeping the MemoryIO to hand requires neither looking at the pointer table nor allocating large memory blocks and dicing them up, if I understand correctly? If you are reading back subsets of regions, slicing seems the more obvious abstraction to me.

Am I still confused?

**Comment by mundya** [comment] 2015-03-17 11:04
> Are you reading back only subsets of regions in nengo? If not, using sdram_alloc for each region and just keeping the MemoryIO to hand requires neither looking at the pointer table nor allocating large memory blocks and dicing them up, if I understand correctly? 

There aren't enough tags available for SDRAM allocing each region, so it has to be a large chunk which is then diced up.

>  slicing seems the more obvious abstraction to me.

In principle I'd agree, but then we should be supporting the buffer interface rather than pretending to be a file.

**Comment by mundya** [comment] 2015-03-17 13:20
I'm currently reading up on correctly aping `memoryview` and meeting NumPy's array interface.  @neworderofjamie do you have any thoughts on making to SpiNNaker memory <-> NumPy array transition smooth? Ideally I guess you might want `some_memory_on_spinnaker[:] = some_numpy_array[:]`?

**Comment by mossblaser** [comment] 2015-03-17 14:12
> There aren't enough tags available for allocing each region on its own, so it has to be a large chunk per core which is then diced up.

My point earlier is that you only need to put a tag on the region with the pointers to other regions (i.e. one tag per core). The host already knows where all regions are (it allocated them) so no tags are needed for its benefit. The machine knows where the table is (it has a tag) and thus where the others are (they're in the table)! Am I getting mixed up?

> I'm currently reading up on correctly aping memoryview and meeting NumPy's array interface.

Could you give me a pointer for those? All I can find is a Cython feature (we're not switching to cython, right?).

**Comment by neworderofjamie** [comment] 2015-03-17 14:15
Aside from syntactically, would the advantage of this over calling tostring() on a numpy array be that it doesn't result in memory being being allocated for a duplicate of the array data?

**Comment by mundya** [comment] 2015-03-17 14:22
> Aside from syntactically, would the advantage of this over calling tostring() on a numpy array be that it doesn't result in memory being being allocated for a duplicate of the array data?

I'm not sure but I can check.  Going the other way this would be true I think.

```python
a = np.frombytes(mem.read(512), dtype=np.uint32)  # Creates and then garbage collects 512b
a = np.array(mem[0:512])  # Could avoid this if implemented intelligently
```

**Comment by neworderofjamie** [comment] 2015-03-17 14:23
More generally, I personally don't think this should be tied to regions as they have a fairly specific meaning in terms of SpiNNaker executables and this is more widely applicable so I'd favour @mossblaser 's slicing approach.

**Comment by mundya** [comment] 2015-03-17 14:26
> More generally, I personally don't think this should be tied to regions as they have a fairly specific meaning in terms of SpiNNaker executables and this is more widely applicable so I'd favour @mossblaser 's slicing approach.

I'm sincerely regretting ever mentioning regions.

On reflection my view is that:
```python
mem = controller.sdram_alloc_as_memoryview(1024*3)
mem[:] = 1024*b"joy"
```
is preferable to
```python
fp = controller.sdram_alloc_as_filelike(1024*3)
fp.write(1024*b"joy")
```

Not least because
```python
do_something_with_half_a_kB(mem[:512])
```
reads nicely and

```python
>>> mem[0:5].tobytes()
b"joyjo"
```
seems sane.

**Comment by neworderofjamie** [comment] 2015-03-17 14:29
But what about seeking? Unless I'm missing something or unless you propose a mask array of where data's actually been written or similar, you'd losing the ability to explicitly seek over padding which would be really useful.

**Comment by mossblaser** [comment] 2015-03-17 14:31
> On reflection my view is that:
> ...

So in summary, a numpy-array-like view of memory would be preferable to a file-like view of memory? Does this mean you can write something which to numpy looks like ordinary memory but which is really some python code being called with addresses and data? Sounds like magic :) (fun magic!)

**Comment by mundya** [comment] 2015-03-17 14:34
> But what about seeking? Unless I'm missing something or unless you propose a mask array of where data's actually been written or similar, you'd losing the ability to explicitly seek over padding which would be really useful.

```python
block_of_data[0:padding] = b'\x00' * padding
meaningful_data = block_of_data[padding:]
```
Where `meaningful_data` acts exactly like `block_of_data` so you can convert it to bytes, write to it, etc.  Seeking isn't necessary if you can just grab references to blocks of memory that are meaningful...

That said, I can see for compressed sparse rows/columns seeking might be handy.

> So in summary, a numpy-array-like view of memory would be preferable to a file-like view of memory? Does this mean you can write something which to numpy looks like ordinary memory but which is really some python code being called with addresses and data? Sounds like magic :) (fun magic!)

That's what I was thinking.  There are benefits to both approaches I think, but I'd like to try supporting this one, maybe.

**Comment by neworderofjamie** [comment] 2015-03-17 14:36
And for not actually writing out recording regions etc

**Comment by mossblaser** [comment] 2015-03-17 14:50
> There are benefits to both approaches I think, but I'd like to try supporting this one, maybe.

My presumption was that Numpy had file-backed arrays (or at least a trivial "put this in a file/take this from a file" interfaces). /me doesn't know anything about this though ;)

In this space, I'm weakly of the opinion that duplicating one memory region worth of data in system memory is not something to be worried about:
* Network performance will be far worse than that copy operation (and will involve (maybe several) copy operations too)
* Max size to be duplicated in one go would be 256 MBytes since the largest copy operation would be one chip-worth at once so this doesn't have enormous memory costs.

**Closed** 2015-04-22 14:13 UTC
Labels: enhancement
